### PR TITLE
make website responsive , fix Navbar, fix text issue , fix image alingment

### PR DESCRIPTION
**Pull request by dipakpatil025**
updations : 
1  - make website fully responsive
2 -  fix navbar issue
3 -  fix image alignment
4 - fix text alignment
5 - add hover effect
6 - fix booter alignment

image

image

image

### CODE REVIEW

**Comment by yashar1908** [comment]
will review soon, great work

**Review by RITEKROUNAK — APPROVED** [review]

**Comment by sanamkandar** [comment]
hello @yashar1908 tagged very merges with "hacktoberfest-accepeted" then it will be counted.

**Comment by RITEKROUNAK** [comment]
@dipakpatil025 yes when the pull request is merged with Hacktoberfest-accepted label then it is counted.

**Comment by RITEKROUNAK** [comment]
I need Some time to merge because its having some merge conflict.

**Comment by sanamkandar** [comment]
> I need Some time to merge because its having some merge conflict.

okay sure

**Comment by RITEKROUNAK** [comment]
Good work. I am merging your PR.

Do give us a star by hitting the star button of this repo!

**Comment by dipakpatil025** [comment]
thanks sir for merge my RP 😊

**Pull request merged**
